spring.application.name=UnitTestingEcom
server.port=8084
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/UnitTestingEcom
spring.datasource.username=postgres
spring.datasource.password=madhu@340
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update